### ISSUE TITLE
楼主您好，能否将每个选项卡页弹出的新增修改删除等模态框，不要遮挡全局页面，只是遮挡当前选项卡页面

### ISSUE THREAD

**Issue by jinwmmail** [zhontai/Admin.UI#1]
楼主您好，能否将每个选项卡页弹出的新增修改删除等模态框，不要遮挡全局页面，只是遮挡当前选项卡页面，这样可以暂停当前选项卡的操作，切换到其它选项卡，以功能急盼回复

**Comment by zhontai** [comment]
element弹窗组件内嵌在当前界面有问题。
