### ISSUE TITLE
请问2.0安装报错要怎么解决？

### ISSUE THREAD

**Issue by 41805556** [zhontai/Admin.UI#8]
D:\vben\zt>npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: admin.ui@2.0.0
npm ERR! Found: eslint@7.21.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.21.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.15
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"4.5.15" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\AnilYu\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AnilYu\AppData\Local\npm-cache\_logs\2022-08-26T13_35_19_752Z-debug-0.log

D:\vben\zt>

**Comment by zhontai** [comment]
npm install --legacy-peer-deps

**Comment by 41805556** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 41805556** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
